#!/usr/bin/env python3
"""3D visualization of a trained policy using viser.

Launch an interactive 3D viewer to play back a quadrotor flight trajectory
generated by a trained policy, with companion time-series plots.

Usage:
    uv run play hover --checkpoint checkpoints/policy/state_hovering_params
    uv run play track --checkpoint checkpoints/policy/traj_tracking_params
    uv run play hover --config configs/state_hovering.yaml --checkpoint checkpoints/policy/my_policy
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Optional

import jax
import jax.numpy as jnp
import numpy as np
import optax
import yaml
from flax.core import FrozenDict
from flax.training.train_state import TrainState
from orbax.checkpoint import PyTreeCheckpointer
from scipy.spatial.transform import Rotation

from lotf import LOTF_ROOT, resolve_path
from lotf.envs.env_base import rollout
from lotf.envs.hovering_state_env import HoveringStateEnv
from lotf.envs.traj_tracking_state_env import TrajTrackingStateEnv
from lotf.envs.wrappers import MinMaxObservationWrapper
from lotf.modules.mlp import MLP
from lotf.objects.quadrotor_obj import Quadrotor


def load_policy_and_env(checkpoint_path: str, config: dict, env_type: str):
    """Load a trained policy checkpoint and recreate its environment."""
    sim_dyn_config = {
        "use_high_fidelity": config.get("sim_dyn_config", {}).get("use_high_fidelity", False),
        "use_forward_residual": config.get("sim_dyn_config", {}).get("use_forward_residual", False),
    }
    sim_dt = config.get("sim_dt", 0.02)
    max_sim_time = config.get("max_sim_time", 5.0)
    delay = config.get("delay", 0.04)

    quad_obj = Quadrotor.from_name("example_quad", sim_dyn_config)

    if env_type == "hover":
        hover_target = config.get("hover_target", [1.5, 0.0, 1.5])
        margin = config.get("margin", 0.5)
        env = HoveringStateEnv(
            max_steps_in_episode=int(max_sim_time / sim_dt),
            dt=sim_dt,
            delay=delay,
            quad_obj=quad_obj,
            margin=margin,
            hover_target=hover_target,
        )
    elif env_type == "track":
        ref_traj_name = config.get("ref_traj_name", "fig8")
        skip_start = config.get("skip_start", True)
        env = TrajTrackingStateEnv(
            max_steps_in_episode=int(max_sim_time / sim_dt),
            dt=sim_dt,
            delay=delay,
            quad_obj=quad_obj,
            ref_traj_name=ref_traj_name,
            skip_start=skip_start,
        )
    else:
        raise ValueError(f"Unknown env_type: {env_type}")

    env = MinMaxObservationWrapper(env)
    action_dim = env.action_space.shape[0]
    obs_dim = env.observation_space.shape[0]

    hidden_layers = config.get("policy_net", {}).get("hidden_layers", [512, 512])
    initial_scale = config.get("policy_net", {}).get("initial_scale", 0.01)
    policy_net = MLP(
        [obs_dim, *hidden_layers, action_dim],
        action_bias=getattr(env, "hovering_action", None),
        initial_scale=initial_scale,
    )

    ckptr = PyTreeCheckpointer()
    ckpt_path = resolve_path(checkpoint_path)
    if not Path(ckpt_path).exists():
        raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}")
    policy_params = ckptr.restore(str(ckpt_path))

    train_state = TrainState.create(
        apply_fn=policy_net.apply,
        params=policy_params,
        tx=optax.adam(1e-3),
    )

    def policy_fn(obs, key):
        return train_state.apply_fn(train_state.params, obs)

    residual_path = LOTF_ROOT / "checkpoints" / "residual_dynamics" / "dummy_params"
    if residual_path.exists():
        residual_params = ckptr.restore(str(residual_path))
    else:
        residual_params = FrozenDict({})

    return policy_fn, env, residual_params


def run_rollout(env, policy_fn, residual_params, seed: int = 0):
    """Run a single rollout and extract full trajectory data.

    Returns:
        positions: (T, 3) positions in world frame [m].
        velocities: (T, 3) velocities in world frame [m/s].
        eulers: (T, 3) Euler angles (roll, pitch, yaw) [deg].
        dt: simulation timestep [s].
        ref_positions: (N, 3) reference trajectory positions (None for hover).
    """
    key = jax.random.key(seed)
    transitions = rollout(env, key, policy_fn, residual_params)

    positions = np.array(transitions.state.quadrotor_state.p)
    velocities = np.array(transitions.state.quadrotor_state.v)
    R = np.array(transitions.state.quadrotor_state.R)  # (T, 3, 3)
    eulers = np.array(
        [Rotation.from_matrix(R[i]).as_euler("xyz", degrees=True) for i in range(len(R))]
    )

    # extract reference trajectory if available (track env)
    ref_positions = None
    if hasattr(env, "ref_traj"):
        ref_positions = np.array(env.ref_traj[:, 1:4])  # pos columns: px, py, pz

    return positions, velocities, eulers, env.dt, ref_positions


def build_time_series_figure(t, positions, velocities, eulers, ref_positions=None, ref_t=None):
    """Build a Plotly figure with pos3D, velocity, and euler angle subplots."""
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots

    fig = make_subplots(
        rows=3,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Position over time", "Velocity over time", "Euler angles over time"),
        vertical_spacing=0.08,
    )

    # Position over time
    fig.add_trace(
        go.Scattergl(x=t, y=positions[:, 0], mode="lines", name="x", line=dict(color="red")),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=positions[:, 1], mode="lines", name="y", line=dict(color="green")),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=positions[:, 2], mode="lines", name="z", line=dict(color="blue")),
        row=1,
        col=1,
    )

    # reference trajectory (dashed) if available
    if ref_positions is not None and ref_t is not None:
        fig.add_trace(
            go.Scattergl(
                x=ref_t,
                y=ref_positions[:, 0],
                mode="lines",
                name="ref_x",
                line=dict(color="red", dash="dash"),
            ),
            row=1,
            col=1,
        )
        fig.add_trace(
            go.Scattergl(
                x=ref_t,
                y=ref_positions[:, 1],
                mode="lines",
                name="ref_y",
                line=dict(color="green", dash="dash"),
            ),
            row=1,
            col=1,
        )
        fig.add_trace(
            go.Scattergl(
                x=ref_t,
                y=ref_positions[:, 2],
                mode="lines",
                name="ref_z",
                line=dict(color="blue", dash="dash"),
            ),
            row=1,
            col=1,
        )

    # Velocity over time
    fig.add_trace(
        go.Scattergl(x=t, y=velocities[:, 0], mode="lines", name="vx", line=dict(color="red")),
        row=2,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=velocities[:, 1], mode="lines", name="vy", line=dict(color="green")),
        row=2,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=velocities[:, 2], mode="lines", name="vz", line=dict(color="blue")),
        row=2,
        col=1,
    )

    # Euler angles over time
    fig.add_trace(
        go.Scattergl(x=t, y=eulers[:, 0], mode="lines", name="roll", line=dict(color="red")),
        row=3,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=eulers[:, 1], mode="lines", name="pitch", line=dict(color="green")),
        row=3,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=eulers[:, 2], mode="lines", name="yaw", line=dict(color="blue")),
        row=3,
        col=1,
    )

    fig.update_xaxes(title_text="Time [s]", row=3, col=1)
    fig.update_yaxes(title_text="Pos [m]", row=1, col=1)
    fig.update_yaxes(title_text="Vel [m/s]", row=2, col=1)
    fig.update_yaxes(title_text="Euler [deg]", row=3, col=1)

    fig.update_layout(
        height=700,
        margin=dict(l=60, r=20, t=30, b=30),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        hovermode="x unified",
    )

    return fig


def launch_viewer(positions, velocities, eulers, dt, ref_positions=None):
    """Launch an interactive 3D viewer with viser and time-series plots.

    Args:
        positions: (T, 3) array of trajectory positions [m].
        velocities: (T, 3) array of velocities [m/s].
        eulers: (T, 3) array of Euler angles [deg].
        dt: simulation timestep [s].
        ref_positions: optional (N, 3) reference trajectory positions.
    """
    import viser

    server = viser.ViserServer(host="127.0.0.1", port=8081)

    T = len(positions)
    t = np.arange(T) * dt

    # 3D trajectory spline
    server.scene.add_spline_catmull_rom(
        "/trajectory",
        positions,
        color=(80, 180, 255),
        segments=200,
        line_width=3.0,
    )

    # reference trajectory (dashed, semi-transparent)
    if ref_positions is not None:
        server.scene.add_spline_catmull_rom(
            "/ref_trajectory",
            ref_positions,
            color=(255, 180, 80),
            segments=min(200, len(ref_positions)),
            line_width=1.5,
        )

    frame_handle = server.scene.add_frame(
        "/frame",
        show_axes=True,
        axes_length=0.5,
        axes_radius=0.02,
    )

    sphere_handle = server.scene.add_icosphere(
        "/drone",
        radius=0.1,
        color=(255, 100, 80),
    )

    text_handle = server.add_gui_text(
        "Timestep",
        initial_value=f"0 / {T - 1}",
    )

    # animation controls
    step = server.add_gui_slider(
        "Step",
        min=0,
        max=T - 1,
        step=1,
        initial_value=0,
    )

    playing = server.add_gui_checkbox("Play", initial_value=True)
    speed = server.add_gui_slider("Speed", min=0.1, max=5.0, step=0.1, initial_value=1.0)

    # bottom time-series plots
    ref_t = None
    if ref_positions is not None:
        ref_t = np.arange(len(ref_positions)) * dt
    fig = build_time_series_figure(t, positions, velocities, eulers, ref_positions, ref_t)
    server.add_gui_plotly(figure=fig)

    @step.on_update
    def _update_step(event):
        i = int(event.target.value)
        pos = positions[i]
        frame_handle.position = pos
        sphere_handle.position = pos
        text_handle.value = f"{i} / {T - 1}"

    fps = 30.0
    while True:
        if playing.value:
            step.value = (step.value + fps * speed.value / T) % T
        time.sleep(1.0 / fps)


def main() -> int:
    """Entry point for the visualize subcommand."""
    parser = argparse.ArgumentParser(
        prog="play",
        description="Play back a trained policy in an interactive 3D viewer.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    uv run play hover
    uv run play hover --checkpoint checkpoints/policy/state_hovering_params_20260506_063520
    uv run play track --checkpoint checkpoints/policy/traj_tracking_params
        """,
    )
    parser.add_argument(
        "env_type",
        choices=["hover", "track"],
        help="Policy type: hover or track",
    )
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=None,
        help="Path to policy checkpoint (auto-detected if omitted)",
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help="Path to YAML config (auto-detected from env_type if omitted)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for rollout (default: 42)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8081,
        help="Port for the viser web server (default: 8081)",
    )

    args = parser.parse_args()

    config_path = (
        args.config
        or f"configs/{'state_hovering' if args.env_type == 'hover' else 'traj_tracking'}.yaml"
    )
    with open(resolve_path(config_path)) as f:
        config = yaml.safe_load(f)

    checkpoint = args.checkpoint
    if checkpoint is None:
        ckpt_dir = LOTF_ROOT / "checkpoints" / "policy"
        if args.env_type == "hover":
            candidates = sorted(
                ckpt_dir.glob("state_hovering_params*"),
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
        else:
            candidates = sorted(
                ckpt_dir.glob("traj_tracking_params*"),
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
        if not candidates:
            print(f"Error: No checkpoints found for {args.env_type} in {ckpt_dir}", file=sys.stderr)
            return 1
        checkpoint = str(candidates[0])
        print(f"Auto-detected checkpoint: {checkpoint}")

    print(f"Loading policy from: {checkpoint}")
    policy_fn, env, residual_params = load_policy_and_env(checkpoint, config, args.env_type)

    print("Running rollout...")
    positions, velocities, eulers, dt, ref_positions = run_rollout(
        env, policy_fn, residual_params, seed=args.seed
    )
    print(f"Rollout complete: {len(positions)} timesteps, dt={dt:.3f}s")

    print(f"Launching 3D viewer at http://127.0.0.1:{args.port}")
    launch_viewer(positions, velocities, eulers, dt, ref_positions)

    return 0


if __name__ == "__main__":
    sys.exit(main())
