#!/usr/bin/env python3
"""3D visualization of a trained policy using viser.

Launch an interactive 3D viewer to play back a quadrotor flight trajectory
generated by a trained policy, with companion time-series plots.

Usage:
    uv run play track --checkpoint checkpoints/policy/traj_tracking_params
"""

from __future__ import annotations

import argparse
import sys
import time

import jax
import numpy as np
from flax.core import FrozenDict
from orbax.checkpoint import PyTreeCheckpointer
from scipy.spatial.transform import Rotation

from lotf import LOTF_ROOT
from lotf.envs.env_base import rollout
from lotf.forward_model_config import (
    SETTING_ORDER,
    checkpoint_name_for_setting,
    get_forward_model_config,
)
from lotf.traj_tracking_setup import (
    TrajTrackingConfig,
    build_traj_tracking_env,
    load_policy_fn,
    load_residual_params,
)


def load_policy_and_env(
    checkpoint_path: str,
    config: TrajTrackingConfig,
    residual_checkpoint: str,
):
    """Load a trained policy checkpoint and recreate its environment."""
    env = build_traj_tracking_env(config, with_log_wrapper=False, with_vec_wrapper=False)

    policy_fn = load_policy_fn(checkpoint_path, config, env)

    if config.forward_model_config.enable_residual_acceleration:
        residual_params = load_residual_params(residual_checkpoint)
        return policy_fn, env, residual_params

    residual_path = LOTF_ROOT / "checkpoints" / "residual_dynamics" / "dummy_params"
    if residual_path.exists():
        residual_params = PyTreeCheckpointer().restore(str(residual_path))
    else:
        residual_params = FrozenDict({})

    return policy_fn, env, residual_params


def run_rollout(env, policy_fn, residual_params, seed: int = 0):
    """Run a single rollout and extract full trajectory data.

    Returns:
        positions: (T, 3) positions in world frame [m].
        velocities: (T, 3) velocities in world frame [m/s].
        eulers: (T, 3) Euler angles (roll, pitch, yaw) [deg].
        dt: simulation timestep [s].
        ref_positions: (N, 3) reference trajectory positions (None for hover).
    """
    key = jax.random.key(seed)
    transitions = rollout(env, key, policy_fn, residual_params)

    positions = np.array(transitions.state.quadrotor_state.p)
    velocities = np.array(transitions.state.quadrotor_state.v)
    R = np.array(transitions.state.quadrotor_state.R)  # (T, 3, 3)
    eulers = np.array(
        [Rotation.from_matrix(R[i]).as_euler("xyz", degrees=True) for i in range(len(R))]
    )

    # extract reference trajectory if available (track env)
    ref_positions = None
    if hasattr(env, "ref_traj"):
        ref_positions = np.array(env.ref_traj[:, 1:4])  # pos columns: px, py, pz

    return positions, velocities, eulers, env.dt, ref_positions


def build_time_series_figure(t, positions, velocities, eulers, ref_positions=None, ref_t=None):
    """Build a Plotly figure with pos3D, velocity, and euler angle subplots."""
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots

    fig = make_subplots(
        rows=3,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Position over time", "Velocity over time", "Euler angles over time"),
        vertical_spacing=0.08,
    )

    # Position over time
    fig.add_trace(
        go.Scattergl(x=t, y=positions[:, 0], mode="lines", name="x", line=dict(color="red")),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=positions[:, 1], mode="lines", name="y", line=dict(color="green")),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=positions[:, 2], mode="lines", name="z", line=dict(color="blue")),
        row=1,
        col=1,
    )

    # reference trajectory (dashed) if available
    if ref_positions is not None and ref_t is not None:
        fig.add_trace(
            go.Scattergl(
                x=ref_t,
                y=ref_positions[:, 0],
                mode="lines",
                name="ref_x",
                line=dict(color="red", dash="dash"),
            ),
            row=1,
            col=1,
        )
        fig.add_trace(
            go.Scattergl(
                x=ref_t,
                y=ref_positions[:, 1],
                mode="lines",
                name="ref_y",
                line=dict(color="green", dash="dash"),
            ),
            row=1,
            col=1,
        )
        fig.add_trace(
            go.Scattergl(
                x=ref_t,
                y=ref_positions[:, 2],
                mode="lines",
                name="ref_z",
                line=dict(color="blue", dash="dash"),
            ),
            row=1,
            col=1,
        )

    # Velocity over time
    fig.add_trace(
        go.Scattergl(x=t, y=velocities[:, 0], mode="lines", name="vx", line=dict(color="red")),
        row=2,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=velocities[:, 1], mode="lines", name="vy", line=dict(color="green")),
        row=2,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=velocities[:, 2], mode="lines", name="vz", line=dict(color="blue")),
        row=2,
        col=1,
    )

    # Euler angles over time
    fig.add_trace(
        go.Scattergl(x=t, y=eulers[:, 0], mode="lines", name="roll", line=dict(color="red")),
        row=3,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=eulers[:, 1], mode="lines", name="pitch", line=dict(color="green")),
        row=3,
        col=1,
    )
    fig.add_trace(
        go.Scattergl(x=t, y=eulers[:, 2], mode="lines", name="yaw", line=dict(color="blue")),
        row=3,
        col=1,
    )

    fig.update_xaxes(title_text="Time [s]", row=3, col=1)
    fig.update_yaxes(title_text="Pos [m]", row=1, col=1)
    fig.update_yaxes(title_text="Vel [m/s]", row=2, col=1)
    fig.update_yaxes(title_text="Euler [deg]", row=3, col=1)

    fig.update_layout(
        height=700,
        margin=dict(l=60, r=20, t=30, b=30),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        hovermode="x unified",
    )

    return fig


def launch_viewer(positions, velocities, eulers, dt, ref_positions=None):
    """Launch an interactive 3D viewer with viser and time-series plots.

    Args:
        positions: (T, 3) array of trajectory positions [m].
        velocities: (T, 3) array of velocities [m/s].
        eulers: (T, 3) array of Euler angles [deg].
        dt: simulation timestep [s].
        ref_positions: optional (N, 3) reference trajectory positions.
    """
    import viser

    server = viser.ViserServer(host="127.0.0.1", port=8081)

    T = len(positions)
    t = np.arange(T) * dt

    # 3D trajectory spline
    server.scene.add_spline_catmull_rom(
        "/trajectory",
        positions,
        color=(80, 180, 255),
        segments=200,
        line_width=3.0,
    )

    # reference trajectory (dashed, semi-transparent)
    if ref_positions is not None:
        server.scene.add_spline_catmull_rom(
            "/ref_trajectory",
            ref_positions,
            color=(255, 180, 80),
            segments=min(200, len(ref_positions)),
            line_width=1.5,
        )

    frame_handle = server.scene.add_frame(
        "/frame",
        show_axes=True,
        axes_length=0.5,
        axes_radius=0.02,
    )

    sphere_handle = server.scene.add_icosphere(
        "/drone",
        radius=0.1,
        color=(255, 100, 80),
    )

    text_handle = server.add_gui_text(
        "Timestep",
        initial_value=f"0 / {T - 1}",
    )

    # animation controls
    step = server.add_gui_slider(
        "Step",
        min=0,
        max=T - 1,
        step=1,
        initial_value=0,
    )

    playing = server.add_gui_checkbox("Play", initial_value=True)
    speed = server.add_gui_slider("Speed", min=0.1, max=5.0, step=0.1, initial_value=1.0)

    # bottom time-series plots
    ref_t = None
    if ref_positions is not None:
        ref_t = np.arange(len(ref_positions)) * dt
    fig = build_time_series_figure(t, positions, velocities, eulers, ref_positions, ref_t)
    server.add_gui_plotly(figure=fig)

    @step.on_update
    def _update_step(event):
        i = int(event.target.value)
        pos = positions[i]
        frame_handle.position = pos
        sphere_handle.position = pos
        text_handle.value = f"{i} / {T - 1}"

    fps = 30.0
    while True:
        if playing.value:
            step.value = (step.value + fps * speed.value / T) % T
        time.sleep(1.0 / fps)


def main() -> int:
    """Entry point for the visualize subcommand."""
    parser = argparse.ArgumentParser(
        prog="play",
        description="Play back a trained policy in an interactive 3D viewer.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    uv run play track --checkpoint checkpoints/policy/traj_tracking_params
        """,
    )
    parser.add_argument(
        "env_type",
        choices=["track"],
        help="Policy type: track",
    )
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=None,
        help="Path to policy checkpoint (auto-detected from --setting if omitted)",
    )
    parser.add_argument(
        "--setting",
        choices=SETTING_ORDER,
        default="full",
        help="Standard setting to play when checkpoint is auto-detected (default: full)",
    )
    parser.add_argument(
        "--checkpoint-stem",
        type=str,
        default="checkpoints/policy/traj_tracking_params",
        help="Base checkpoint stem for setting-based auto-detection",
    )
    parser.add_argument(
        "--residual-checkpoint",
        type=str,
        default="checkpoints/residual_dynamics/residual_params",
        help="Residual dynamics checkpoint for resacc/full playback",
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help="Path to YAML config (auto-detected from env_type if omitted)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for rollout (default: 42)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8081,
        help="Port for the viser web server (default: 8081)",
    )

    args = parser.parse_args()

    config_path = args.config or "configs/traj_tracking.yaml"
    config = TrajTrackingConfig.from_yaml(config_path)
    config.forward_model_config = get_forward_model_config(args.setting)

    checkpoint = args.checkpoint
    if checkpoint is None:
        expected = checkpoint_name_for_setting(LOTF_ROOT / args.checkpoint_stem, args.setting)
        candidates = sorted(
            expected.parent.glob(f"{expected.name}*"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not candidates:
            print(
                f"Error: No {args.setting} checkpoints found. "
                f"Expected pattern: {expected.parent / (expected.name + '*')}",
                file=sys.stderr,
            )
            print(f"Train it with: uv run train track --setting {args.setting}", file=sys.stderr)
            return 1
        checkpoint = str(candidates[0])
        print(f"Auto-detected checkpoint: {checkpoint}")

    print(f"Loading policy from: {checkpoint}")
    try:
        policy_fn, env, residual_params = load_policy_and_env(
            checkpoint,
            config,
            args.residual_checkpoint,
        )
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    print("Running rollout...")
    positions, velocities, eulers, dt, ref_positions = run_rollout(
        env, policy_fn, residual_params, seed=args.seed
    )
    print(f"Rollout complete: {len(positions)} timesteps, dt={dt:.3f}s")

    print(f"Launching 3D viewer at http://127.0.0.1:{args.port}")
    launch_viewer(positions, velocities, eulers, dt, ref_positions)

    return 0


if __name__ == "__main__":
    sys.exit(main())
